name: gradus-rl
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - numpy
  - pip
  - pip:
    - genesis-world
    - gymnasium
    - tensorboard
    - matplotlib
