name: gradus-rl
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu126
    - "torch>=2.8.0"
    - torchvision
    - torchaudio
    - genesis-world
    - gymnasium
    - tensorboard
    - matplotlib
    - "rsl-rl-lib>=5.0.0"